#!/bin/sh

printf "# "
echo "generated by" $0
echo

nameOfFolder="gamedatamap"

echo "${nameOfFolder}dir = ""$""(""datadir"")""/""@""PACKAGE""@""/map"

printf "${nameOfFolder}_DATA = "

items=`find . -type f -print`

howManyLines=`printf "${items}" | wc -l`
currentLine=0

echo "${items}" | while read line; do
        lineToPrint=$line
        if [ `printf "%s" $line | cut -c 1-2` = "./" ]; then
            lineToPrint=`printf "%s" $line | cut -c 3-`
        fi

        if [ ! $line = $0 ]; then
                if [ ! $lineToPrint = "Makefile.am" ]; then
                        if [ $currentLine -gt 0 ]; then
                                printf "\t\t\t"
                        fi

                        printf "%s" $lineToPrint

                        if [ $currentLine -lt $howManyLines ]; then
                                printf " \\"
                        fi
                        echo
                fi
        fi

        currentLine=`expr $currentLine + 1`
done
